const COUNTRIES = [
  { name: "Afghanistan", code: "af" },
  { name: "Albania", code: "al" },
  { name: "Algeria", code: "dz" },
  { name: "Andorra", code: "ad" },
  { name: "Angola", code: "ao" },
  { name: "Arabia Saudita", code: "sa" },
  { name: "Argentina", code: "ar" },
  { name: "Armenia", code: "am" },
  { name: "Australia", code: "au" },
  { name: "Austria", code: "at" },
  { name: "Azerbaigian", code: "az" },
  { name: "Bahamas", code: "bs" },
  { name: "Bahrain", code: "bh" },
  { name: "Bangladesh", code: "bd" },
  { name: "Belgio", code: "be" },
  { name: "Belize", code: "bz" },
  { name: "Benin", code: "bj" },
  { name: "Bhutan", code: "bt" },
  { name: "Bielorussia", code: "by" },
  { name: "Bolivia", code: "bo" },
  { name: "Bosnia ed Erzegovina", code: "ba" },
  { name: "Botswana", code: "bw" },
  { name: "Brasile", code: "br" },
  { name: "Brunei", code: "bn" },
  { name: "Bulgaria", code: "bg" },
  { name: "Burkina Faso", code: "bf" },
  { name: "Burundi", code: "bi" },
  { name: "Cambogia", code: "kh" },
  { name: "Camerun", code: "cm" },
  { name: "Canada", code: "ca" },
  { name: "Capo Verde", code: "cv" },
  { name: "Ciad", code: "td" },
  { name: "Cile", code: "cl" },
  { name: "Cina", code: "cn" },
  { name: "Cipro", code: "cy" },
  { name: "Colombia", code: "co" },
  { name: "Comore", code: "km" },
  { name: "Congo", code: "cg" },
  { name: "Corea del Nord", code: "kp" },
  { name: "Corea del Sud", code: "kr" },
  { name: "Costa Rica", code: "cr" },
  { name: "Costa d'Avorio", code: "ci" },
  { name: "Croazia", code: "hr" },
  { name: "Cuba", code: "cu" },
  { name: "Danimarca", code: "dk" },
  { name: "Ecuador", code: "ec" },
  { name: "Egitto", code: "eg" },
  { name: "El Salvador", code: "sv" },
  { name: "Emirati Arabi Uniti", code: "ae" },
  { name: "Eritrea", code: "er" },
  { name: "Estonia", code: "ee" },
  { name: "Etiopia", code: "et" },
  { name: "Fiji", code: "fj" },
  { name: "Filippine", code: "ph" },
  { name: "Finlandia", code: "fi" },
  { name: "Francia", code: "fr" },
  { name: "Gabon", code: "ga" },
  { name: "Gambia", code: "gm" },
  { name: "Georgia", code: "ge" },
  { name: "Germania", code: "de" },
  { name: "Ghana", code: "gh" },
  { name: "Giamaica", code: "jm" },
  { name: "Giappone", code: "jp" },
  { name: "Gibuti", code: "dj" },
  { name: "Giordania", code: "jo" },
  { name: "Grecia", code: "gr" },
  { name: "Guatemala", code: "gt" },
  { name: "Guinea", code: "gn" },
  { name: "Guinea-Bissau", code: "gw" },
  { name: "Guinea Equatoriale", code: "gq" },
  { name: "Guyana", code: "gy" },
  { name: "Haiti", code: "ht" },
  { name: "Honduras", code: "hn" },
  { name: "India", code: "in" },
  { name: "Indonesia", code: "id" },
  { name: "Iran", code: "ir" },
  { name: "Iraq", code: "iq" },
  { name: "Irlanda", code: "ie" },
  { name: "Islanda", code: "is" },
  { name: "Israele", code: "il" },
  { name: "Italia", code: "it" },
  { name: "Kazakhstan", code: "kz" },
  { name: "Kenya", code: "ke" },
  { name: "Kirghizistan", code: "kg" },
  { name: "Kiribati", code: "ki" },
  { name: "Kosovo", code: "xk" },
  { name: "Kuwait", code: "kw" },
  { name: "Laos", code: "la" },
  { name: "Lesotho", code: "ls" },
  { name: "Lettonia", code: "lv" },
  { name: "Libano", code: "lb" },
  { name: "Liberia", code: "lr" },
  { name: "Libia", code: "ly" },
  { name: "Liechtenstein", code: "li" },
  { name: "Lituania", code: "lt" },
  { name: "Lussemburgo", code: "lu" },
  { name: "Macedonia del Nord", code: "mk" },
  { name: "Madagascar", code: "mg" },
  { name: "Malawi", code: "mw" },
  { name: "Maldive", code: "mv" },
  { name: "Malesia", code: "my" },
  { name: "Mali", code: "ml" },
  { name: "Malta", code: "mt" },
  { name: "Marocco", code: "ma" },
  { name: "Mauritania", code: "mr" },
  { name: "Mauritius", code: "mu" },
  { name: "Messico", code: "mx" },
  { name: "Moldavia", code: "md" },
  { name: "Monaco", code: "mc" },
  { name: "Mongolia", code: "mn" },
  { name: "Montenegro", code: "me" },
  { name: "Mozambico", code: "mz" },
  { name: "Myanmar", code: "mm" },
  { name: "Namibia", code: "na" },
  { name: "Nepal", code: "np" },
  { name: "Nicaragua", code: "ni" },
  { name: "Niger", code: "ne" },
  { name: "Nigeria", code: "ng" },
  { name: "Norvegia", code: "no" },
  { name: "Nuova Zelanda", code: "nz" },
  { name: "Oman", code: "om" },
  { name: "Pakistan", code: "pk" },
  { name: "Palau", code: "pw" },
  { name: "Panama", code: "pa" },
  { name: "Papua Nuova Guinea", code: "pg" },
  { name: "Paraguay", code: "py" },
  { name: "Paesi Bassi", code: "nl" },
  { name: "Perù", code: "pe" },
  { name: "Polonia", code: "pl" },
  { name: "Portogallo", code: "pt" },
  { name: "Qatar", code: "qa" },
  { name: "Regno Unito", code: "gb" },
  { name: "Repubblica Ceca", code: "cz" },
  { name: "Repubblica Centrafricana", code: "cf" },
  { name: "Repubblica Democratica del Congo", code: "cd" },
  { name: "Repubblica Dominicana", code: "do" },
  { name: "Romania", code: "ro" },
  { name: "Ruanda", code: "rw" },
  { name: "Russia", code: "ru" },
  { name: "San Marino", code: "sm" },
  { name: "Senegal", code: "sn" },
  { name: "Serbia", code: "rs" },
  { name: "Sierra Leone", code: "sl" },
  { name: "Singapore", code: "sg" },
  { name: "Siria", code: "sy" },
  { name: "Slovacchia", code: "sk" },
  { name: "Slovenia", code: "si" },
  { name: "Somalia", code: "so" },
  { name: "Spagna", code: "es" },
  { name: "Sri Lanka", code: "lk" },
  { name: "Sudafrica", code: "za" },
  { name: "Sudan", code: "sd" },
  { name: "Sudan del Sud", code: "ss" },
  { name: "Suriname", code: "sr" },
  { name: "Svezia", code: "se" },
  { name: "Svizzera", code: "ch" },
  { name: "Tagikistan", code: "tj" },
  { name: "Tanzania", code: "tz" },
  { name: "Thailandia", code: "th" },
  { name: "Timor Est", code: "tl" },
  { name: "Togo", code: "tg" },
  { name: "Trinidad e Tobago", code: "tt" },
  { name: "Tunisia", code: "tn" },
  { name: "Turchia", code: "tr" },
  { name: "Turkmenistan", code: "tm" },
  { name: "Uganda", code: "ug" },
  { name: "Ucraina", code: "ua" },
  { name: "Ungheria", code: "hu" },
  { name: "Uruguay", code: "uy" },
  { name: "Uzbekistan", code: "uz" },
  { name: "Vanuatu", code: "vu" },
  { name: "Venezuela", code: "ve" },
  { name: "Vietnam", code: "vn" },
  { name: "Yemen", code: "ye" },
  { name: "Zambia", code: "zm" },
  { name: "Zimbabwe", code: "zw" },
];

export default COUNTRIES;
